// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gymnasticHovedOpgave.Models;

#nullable disable

namespace gymnasticHovedOpgave.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250419092851_AddInstructorsToPlanningEvent")]
    partial class AddInstructorsToPlanningEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gymnasticHovedOpgave.Interfaces.PlanningEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("InstructorsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlanningEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatorId = 1,
                            Date = 638054496000000000L,
                            Description = "Training session for all teams.",
                            InstructorsId = "[1,2]",
                            Name = "Gymnastics Training",
                            TeamId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatorId = 2,
                            Date = 638066592000000000L,
                            Description = "Annual competition for all teams.",
                            InstructorsId = "[3,4]",
                            Name = "Annual Gymnastics Championship",
                            TeamId = 2,
                            VenueId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
